In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from tqdm import tqdm_notebook as tqdm
%matplotlib inline

In [3]:
os.listdir('../../data/')

['mulliken_charges.csv',
 'test.csv',
 'structures.csv',
 'dipole_moments.csv',
 'potential_energy.csv',
 'train.csv',
 'scalar_coupling_contributions.csv',
 'magnetic_shielding_tensors.csv',
 'sample_submission.csv']

In [8]:
magnetic_shielding_df = pd.read_csv('../../data/magnetic_shielding_tensors.csv')
train_df = pd.read_csv('../../data/train.csv')
structure_df = pd.read_csv('../../data/structures.csv')
test_df = pd.read_csv('../../data/test.csv')

In [9]:
magnetic_shielding_df.head(20)

,molecule_name,atom_index,XX,YX,ZX,XY,YY,ZY,XZ,YZ,ZZ
0,dsgdb9nsd_000001,0,195.3150,0.0000,-0.0001,0.0000,195.3170,0.0007,-0.0001,0.0007,195.3170
1,dsgdb9nsd_000001,1,31.3410,-1.2317,4.0544,-1.2317,28.9546,-1.7173,4.0546,-1.7173,34.0861
2,dsgdb9nsd_000001,2,31.5814,1.2173,-4.1474,1.2173,28.9036,-1.6036,-4.1476,-1.6036,33.8967
3,dsgdb9nsd_000001,3,31.5172,4.1086,1.2723,4.1088,33.9068,1.6950,1.2724,1.6951,28.9579
4,dsgdb9nsd_000001,4,31.4029,-4.0942,-1.1793,-4.0944,34.0776,1.6259,-1.1795,1.6260,28.9013
5,dsgdb9nsd_000002,0,275.6350,0.0003,0.0133,0.0003,275.6360,-0.0003,0.0161,-0.0004,237.4970
6,dsgdb9nsd_000002,1,31.2593,5.6126,-2.1025,5.6136,37.4364,-3.5567,-2.4461,-4.1372,27.9884
7,dsgdb9nsd_000002,2,31.0341,-5.4827,-2.0299,-5.4837,37.6618,3.5987,-2.3616,4.1861,27.9885
8,dsgdb9nsd_000002,3,40.7507,-0.1300,4.1318,-0.1300,27.9413,-0.0419,4.8083,-0.0488,27.9889
9,dsgdb9nsd_000003,0,310.0960,0.0000,0.0000,0.0000,355.7730,0.0000,0.0000,0.0000,324.1550
10,dsgdb9nsd_000003,1,24.6745,0.0000,0.0000,0.0000,39.1730,-6.6879,0.0000,-8.8417,31.6296
11,dsgdb9nsd_000003,2,24.6745,0.0000,0.0000,0.0000,39.1730,6.6879,0.0000,8.8417,31.6296
12,dsgdb9nsd_000005,0,0.0482,0.0000,0.0000,0.0000,0.0482,0.0000,0.0000,0.0000,278.2650
13,dsgdb9nsd_000005,1,-180.1310,0.0000,0.0000,0.0000,-180.1310,0.0000,0.0000,0.0000,339.6940
14,dsgdb9nsd_000005,2,24.3125,0.0000,0.0000,0.0000,24.3125,0.0000,0.0000,0.0000,39.0232
15,dsgdb9nsd_000007,0,190.3620,0.0004,0.0008,0.0001,177.0150,0.0007,0.0008,0.0005,177.0100
16,dsgdb9nsd_000007,1,190.3620,0.0005,0.0009,0.0002,177.0150,0.0006,0.0009,0.0007,177.0100
17,dsgdb9nsd_000007,2,31.7293,-2.8940,3.3643,-2.1656,29.7981,-3.3396,2.5174,-3.3395,30.8073
18,dsgdb9nsd_000007,3,31.7292,-1.4667,-4.1883,-1.0976,27.6631,2.1074,-3.1340,2.1072,32.9420
19,dsgdb9nsd_000007,4,31.7291,4.3606,0.8240,3.2632,33.4467,1.2323,0.6166,1.2323,27.1580

In [32]:
train_df.head(30)

,id,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant
0,0,dsgdb9nsd_000001,1,0,1JHC,84.80760
1,1,dsgdb9nsd_000001,1,2,2JHH,-11.25700
2,2,dsgdb9nsd_000001,1,3,2JHH,-11.25480
3,3,dsgdb9nsd_000001,1,4,2JHH,-11.25430
4,4,dsgdb9nsd_000001,2,0,1JHC,84.80740
5,5,dsgdb9nsd_000001,2,3,2JHH,-11.25410
6,6,dsgdb9nsd_000001,2,4,2JHH,-11.25480
7,7,dsgdb9nsd_000001,3,0,1JHC,84.80930
8,8,dsgdb9nsd_000001,3,4,2JHH,-11.25430
9,9,dsgdb9nsd_000001,4,0,1JHC,84.80950
10,10,dsgdb9nsd_000002,1,0,1JHN,32.68890
11,11,dsgdb9nsd_000002,1,2,2JHH,-11.18660
12,12,dsgdb9nsd_000002,1,3,2JHH,-11.17570
13,13,dsgdb9nsd_000002,2,0,1JHN,32.68910
14,14,dsgdb9nsd_000002,2,3,2JHH,-11.17580
15,15,dsgdb9nsd_000002,3,0,1JHN,32.69050
16,16,dsgdb9nsd_000003,1,2,2JHH,-9.94641
17,17,dsgdb9nsd_000005,2,0,1JHC,171.22000
18,18,dsgdb9nsd_000005,2,1,2JHN,5.18246
19,19,dsgdb9nsd_000007,2,0,1JHC,83.54290
20,20,dsgdb9nsd_000007,2,1,2JHC,-2.37831
21,21,dsgdb9nsd_000007,2,3,2JHH,-11.70050
22,22,dsgdb9nsd_000007,2,4,2JHH,-11.69790
23,23,dsgdb9nsd_000007,2,5,3JHH,3.25281
24,24,dsgdb9nsd_000007,2,6,3JHH,13.69130
25,25,dsgdb9nsd_000007,2,7,3JHH,3.25205
26,26,dsgdb9nsd_000007,3,0,1JHC,83.54170
27,27,dsgdb9nsd_000007,3,1,2JHC,-2.37862
28,28,dsgdb9nsd_000007,3,4,2JHH,-11.69960
29,29,dsgdb9nsd_000007,3,5,3JHH,13.69240

In [10]:
magnetic_shielding_df.shape

(1533537, 11)

In [20]:
add = np.zeros((len(train_df),18),dtype=np.float32)
stock = None
molecule_name_atom = None
for i,row in tqdm(train_df.iterrows(),total=len(train_df)):
    if stock != row[1]:
        stock = row[1]
        molecule_name_atom = magnetic_shielding_df[magnetic_shielding_df['molecule_name']==stock].values
    add[i,0] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[2])[0],2]
    add[i,1] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[3])[0],2]
    add[i,2] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[2])[0],3]
    add[i,3] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[3])[0],3]
    add[i,4] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[2])[0],4]
    add[i,5] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[3])[0],4]
    add[i,6] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[2])[0],5]
    add[i,7] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[3])[0],5]
    add[i,8] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[2])[0],6]
    add[i,9] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[3])[0],6]
    add[i,10] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[2])[0],7]
    add[i,11] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[3])[0],7]
    add[i,12] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[2])[0],8]
    add[i,13] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[3])[0],8]
    add[i,14] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[2])[0],9]
    add[i,15] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[3])[0],9]
    add[i,16] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[2])[0],10]
    add[i,17] = molecule_name_atom[np.where(molecule_name_atom[:,1]==row[3])[0],10]

HBox(children=(IntProgress(value=0, max=4658147), HTML(value='')))

In [21]:
#pd.to_pickle(add, '../magnetic_shielding_tensors.pkl')